[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/assets/well-known/assetlinks.json"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}